name: Android CI

on:
  push:
    branches:
      - master
      - develop
      - feature/**
      - task/**
      - hotfix/**
  pull_request:
    branches:
      - master
      - develop
      - feature/**
      - task/**
      - hotfix/**

jobs:
  build:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Check code format with Spotless
        run: ./gradlew spotlessCheck --build-cache --parallel

      - name: Run static code analysis with Detekt
        run: ./gradlew detekt --build-cache --parallel

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --build-cache --parallel

      - name: Build app and feature demos
        run: ./gradlew assembleDebug --build-cache --parallel
